// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background_column_left': string;
  'background_column_right': string;
  'background_columns': string;
  'main': string;
  'main_container': string;
  'text_center': string;
}
declare const cssExports: CssExports;
export = cssExports;
