// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'main': string;
  'main_container': string;
}
declare const cssExports: CssExports;
export = cssExports;
